---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-remote
  namespace: cluster-02
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./k8s-platform/flux/v2.2.2
  prune: true
  kubeConfig:
    secretRef:
      name: cluster-02-kubeconfig
