---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-remote
  namespace: cluster-01
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./k8s-platform/flux/v2.2.2
  prune: true
  kubeConfig:
    secretRef:
      name: cluster-01-kubeconfig
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: caaph-cni
  namespace: cluster-01
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./k8s-platform/cni-caaph-resource/cilium/v1.15.2
  targetNamespace: cluster-01
  prune: true
  dependsOn:
  - name: caaph
    namespace: flux-system
