apiVersion: clusterctl.cluster.x-k8s.io/v1alpha3
kind: ClusterctlConfig
providers:
  - name: cluster-api
    url: "https://github.com/kubernetes-sigs/cluster-api/releases/download/v1.5.2"
    type: CoreProvider
  - name: kubeadm
    url: "https://github.com/kubernetes-sigs/cluster-api/releases/download/v1.5.2/bootstrap-components.yaml"
    type: BootstrapProvider
  - name: aws
    url: "https://github.com/kubernetes-sigs/cluster-api-provider-aws/releases/download/v2.3.1/infrastructure-components.yaml"
    type: InfrastructureProvider

variables:
  KUBERNETES_VERSION: "1.28.5"
  AWS_CONTROL_PLANE_MACHINE_TYPE: "t3.medium"
  AWS_NODE_MACHINE_TYPE: "t3.medium"
  CONTROL_PLANE_MACHINE_COUNT: "1"
  WORKER_MACHINE_COUNT: "1"
  CLUSTER_NAME: "cluster-mgmt"
  POD_CIDR: "192.168.16.0/20"
