# platform components that need to be installed on this cluster.
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: caaph
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./k8s-platform/cluster-api-addon-provider-helm
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: caaph-cni
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./k8s-platform/cni-caaph-resource/cilium/v1.12.3
  targetNamespace: cluster-mgmt
  prune: true
  dependsOn:
  - name: caaph
