apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: caaph-cni
  namespace: cluster-mgmt
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./clusters/tmp-mgmt/cluster-mgmt/caaph-hcp-no-mesh-v1.15.2.yaml
  targetNamespace: cluster-mgmt
  prune: true
  dependsOn:
  - name: caaph
    namespace: flux-system
