apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - platform.yaml
  - capi-cluster.yaml
patches:
- path: patch.yaml
  target:
    group: addons.cluster.x-k8s.io
    version: v1alpha1
    kind: HelmChartProxy
    name: cilium-no-mesh
