---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-remote
  namespace: cluster-mgmt
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./clusters/cluster-mgmt/flux-system
  prune: true
  kubeConfig:
    secretRef:
      name: cluster-mgmt-kubeconfig
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: caaph-cni
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/tmp-mgmt/cluster-mgmt/caaph-cni
  targetNamespace: cluster-mgmt
  prune: true
  dependsOn:
  - name: caaph
    namespace: flux-system
