apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/crs-cm-cillium-1.11.5.yaml
  - ../base/crs.yaml
  - ../base/gotk-sync.yaml

patches:

- target:
    group: source.toolkit.fluxcd.io
    version: v1beta2
    kind: GitRepository
    name: flux-system
  patch: |-
    - op: replace
      path: /spec/ref/branch
      value: develop
    - op: replace
      path: /spec/url
      value: ssh://git@github.com/olga-mir/k8s-multi-cluster

- target:
    group: kustomize.toolkit.fluxcd.io/
    version: v1beta2
    kind: Kustomization
    name: flux-system
  patch: |-
    - op: replace
      path: /spec/path
      value: ./clusters/tmp-mgmt
- target:
    group: ""
    version: v1
    kind: ConfigMap
    name: crs-cm-cilium-1.11.5
  patch: |-
    - op: add
      path: /metadata/namespace
      value: cluster-mgmt

- target:
    group: addons.cluster.x-k8s.io
    version: v1beta1
    kind: ClusterResourceSet
    name: crs
  patch: |-
    - op: add
      path: /spec/resources/0/name
      value: crs-cm-cilium-1.11.5
    - op: add
      path: /spec/resources/0/kind
      value: ConfigMap
