CLUSTER_NAME: "dev"
KUBERNETES_VERSION: "1.22.8"
AWS_CONTROL_PLANE_MACHINE_TYPE: "t3.medium"
AWS_NODE_MACHINE_TYPE: "t3.medium"
CONTROL_PLANE_MACHINE_COUNT: "1"
WORKER_MACHINE_COUNT: "1"
EXP_CLUSTER_RESOURCE_SET: "true"
