version: '3'

tasks:
  build-app:
    cmds:
      - go build -v ./cmd/multicluster-demo
    desc: Build the multicluster-demo application
    generates:
      - multicluster-demo

  build-project:
    deps: [build-app]
    cmds:
      - ./multicluster-demo build --config .
    desc: Runs multicluster-demo `build` which builds clusters as defined in the config.yaml file
    sources:
      - "**/*.go"
      - go.mod
      - go.sum
    method: checksum

  test:
    cmds:
      - go test -v ./pkg/...
    desc: Run all tests in the pkg directory

