apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - cluster.yaml
  - crs-cm-flux-${FLUXCD_VERSION}-workload.yaml
  - ../../base/crs.yaml

patches:
- target:
    group: addons.cluster.x-k8s.io
    version: v1beta1
    kind: ClusterResourceSet
    name: crs
  patch: |-
    - op: add
      path: /metadata/namespace
      value: ${CLUSTER_NAME}
    - op: replace
      path: /spec/resources/0/name
      value: crs-cm-flux-${FLUXCD_VERSION}-workload
    - op: replace
      path: /spec/resources/0/kind
      value: ConfigMap
